# Default values for application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Deployment configuration
deployment:
  # Set type to "Deployment" for stateless applications or "StatefulSet" for stateful applications
  type: "Deployment"
  # Enable persistence for StatefulSet
  persistence:
    enabled: false
    size: "1Gi"
    mountPath: "/usr/share/my-app" # Container mount path
    volumeName: "cat-storage" # Volume name
    storageClass: "local-path"

# Application configuration
replicaCount: 2
annotations: {}

# Container image configuration
image:
  repository: ghcr.io/dungxtd/heap-paper
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "main@sha256:ee8a1c02ed8b3e71fe0661315d0df67f46d2f66110fedfbb4d926da6b19457b2"

# Container port configuration
containerPorts:
- name: http
  containerPort: 8080
  protocol: TCP

# Probe configuration
livenessProbe:
  enabled: true
  path: /healthz
  port: http
  initialDelaySeconds: 3
  periodSeconds: 3
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /healthz
  port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

# Environment variables
env: []
  # - name: ENV_NAME
  #   value: env_value
  # - name: SECRET_ENV
  #   valueFrom:
  #     secretKeyRef:
  #       name: secret-name
  #       key: secret-key

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

# Pod security configuration
podSecurityContext:
  fsGroup: 2000
  # Add more security contexts as needed
  # runAsUser: 1000
  # runAsGroup: 3000

  # Container security configuration
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  privileged: false
  allowPrivilegeEscalation: false

# Service configuration
service:
  type: ClusterIP # Can be ClusterIP, NodePort, or LoadBalancer
  port: 8080
  targetPort: http # References containerPort name
  # nodePort: 30000  # Only used when service.type is NodePort

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

  # Resource configuration
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
